# Docker compose for launching Kafka Server

version: "3"
networks:
  cloud-network:
    driver: bridge
services:
# We create all services related to Kafka (Event and Data distribution)
  zookeeper:
    restart: always
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "22181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - './kafka-storage/zookeeper/data:/var/lib/zookeeper/data'
      - './kafka-storage/zookeeper/log:/var/lib/zookeeper/log'
    networks:
      - cloud-network
    
  kafka:
    restart: always
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - "29092:29092"
      - "29093:29093"
    environment:
      KAFKA_BROKER_ID: 1      
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,EXTERNAL_DIFFERENT_HOST://:29093,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092,EXTERNAL_DIFFERENT_HOST://192.168.5.242:29093 # Change last ip by the server (core) ip
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT,EXTERNAL_DIFFERENT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL      
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1      
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - './kafka-storage/kafka/data:/var/lib/kafka/data'
      - './kafka-storage/kafka/secrets:/etc/kafka/secrets'
    networks:
      - cloud-network
    depends_on:
      - zookeeper
    #healthcheck:
    #  test: ["CMD-SHELL", "kafka-topics --bootstrap-server 127.0.0.1:9092 --topic healthcheck --describe"]
    #  interval: 15s
    #  timeout: 10s
    #  retries: 10
  
  kafdrop:
    restart: always
    container_name: kafdrop
    platform: linux/amd64 # Needed for running in Mac Silicon (remember to activate Roseta emulation in settings - Docker)
    image: obsidiandynamics/kafdrop:latest  
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    networks:
      - cloud-network
    depends_on:
      zookeeper:
        condition: service_started
      kafka:
        condition: service_started

